LitReview/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from core import views


urlpatterns = [
    path('', views.connection, name="connection"),
    path('logout/', views.logout, name="logout"),
    path('home/', views.home, name="home"),
    path('ticket/', views.create_ticket, name="create_ticket"),
    path('posts/', include('core.urls')),
    path('userfollows/', include('userfollows.urls')),
    path('review/', include('review.urls', namespace="review")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(
                settings.MEDIA_URL,
                document_root=settings.MEDIA_ROOT)
urlpatterns += static(
                settings.STATIC_URL,
                document_root=settings.STATIC_ROOT)

core/urls.py
from django.conf.urls.static import static
from django.urls import path, re_path
from django.conf import settings
from core import views


urlpatterns = [
    path('register/', views.register_request, name="register_request"),
    path('login/', views.login_request, name="login_request"),
    re_path('update/(?P<post_id>.*)', views.update_ticket, name="update_ticket"),
    re_path('delete/(?P<post_id>.*)', views.delete_ticket, name="delete_ticket"),
    path('', views.posts, name="posts"),
]

if settings.DEBUG:
    urlpatterns += static(
                    settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path, re_path
from . import views

app_name = "review"

urlpatterns = [
    path('update/<int:id_review>/post/<int:id_post>', views.update_review, name="update_review"),
    re_path('create/(?P<id_post>.*)',
        views.create_review_post, name="create_review_post"),
    path('', views.create_review, name="create_review"),
]

review/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from core.models import Ticket
from core.models import User


class Review(models.Model):
    """
    A class to represent a review
        ticket : foreigner key
            a id of ticket/post
        rating : float
            a rating linked to a review
        user : foreigner key
            a id of review's author
        headline : str
            a headline of a review
        body : str
            a body of a review
        time_created :
            the time when the review is created
    """
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

review/forms.py
from django.forms import ModelForm
from .models import Review


class NewReviewForm(ModelForm):
    """
        A class to represent a form for a new review

        Attributes
        ----------
        healdine :str
        body : str
        rating : str
    """
    class Meta:
        model = Review
        fields = [
            "headline",
            "body",
            "rating",
            ]

    def save(self, user, ticket, review_id, commit=True,):
        if review_id is None:
            review = super(NewReviewForm, self).save(commit=False)
        else:
            review = Review.objects.get(id=review_id)
        review.user = user
        review.ticket = ticket
        if commit:
            review.save()
        return review

review/views.py
from django.shortcuts import render, redirect
from core.models import Ticket, User
from core.forms import NewTicketForm
from review.models import Review
from .forms import NewReviewForm


def create_review(request):
    """
        creates a review
    Parameter :
        request : HTTPrequest
    Returns :
        context : Httrrequest
        context : Dict
        template : HTML page
    """
    if request.method == "POST":
        ticket_form = NewTicketForm(request.POST, request.FILES)
        review_form = NewReviewForm(request.POST)
        if ticket_form.is_valid() and review_form.is_valid():
            ticket = ticket_form.save(request.user.id)
            user = User.objects.filter(username=request.user)
            review_form.save(review_id=None, user=user[0], ticket=ticket)
        return redirect("home")
    else:
        ticket_form = NewTicketForm()
        review_form = NewReviewForm()
        return render(
            request=request,
            template_name="review.html",
            context={
                    "ticket_form": ticket_form,
                    "review_form": review_form
                    }
        )


def create_review_post(request, id_post):
    """
    create a review linked a post
    Parameter :
        request : HTTPrequest
        id_post : str
            the id of the post
    Returns :
        context : Httprequest
        context : Dict
        template : HTML page
    """
    ticket = Ticket.objects.filter(id=id_post)
    if request.method == "GET":
        review_form = NewReviewForm()
        return render(
                request=request,
                template_name="review_create_post.html",
                context={
                    "ticket_form_id": ticket[0].id,
                    "ticket_form": ticket,
                    "review_form": review_form}
            )
    else:
        review_form = NewReviewForm(request.POST)
        score = request.POST.get('val')
        print(score)
        review_form.rating = score
        if review_form.is_valid():
            user = User.objects.filter(username=request.user)
            print(score)
            review_form.save(user=user[0], ticket=ticket[0], review_id=None)
        return redirect("home")


def update_review(request, id_review, id_post):
    """
    update a review linked a post
    Parameter :
        request : HTTPrequest
        id_post : str
            the id of the post
        id_review : str
            the id og the review
    Returns :
        context : Httrrequest
        context : Dict
        template : HTML page
    """
    review_toUpdate = Review.objects.get(id=id_review)
    post_reviewed = Ticket.objects.get(id=id_post)
    if request.method == "GET":
        review_form = NewReviewForm(instance=review_toUpdate)
        return render(
                request=request,
                template_name="update_review.html",
                context={
                    "id_post": post_reviewed.id,
                    "id_review": review_toUpdate.id,
                    "review_form": review_form,
                    "ticket_form": post_reviewed
                    }
            )
    elif request.method == "POST":
        review_form = NewReviewForm(request.POST)
        if review_form.is_valid():
            user = User.objects.filter(username=request.user)
            review_toUpdate.headline = review_form.cleaned_data.get("headline")
            review_toUpdate.body = review_form.cleaned_data.get("body")
            review_toUpdate.rating = review_form.cleaned_data.get("rating")
            review_toUpdate.ticket_id = id_post
            review_toUpdate.user_id = user[0].id
            review_toUpdate.save()
        return redirect("home")

review/templates/modify_post.html
{% extends 'core/base.html' %} {% block menu%} {%include 'core/menu.html'%} {% endblock%} {% block content %}
<H1>Modifier un ticket</H1>
<form action="{% url 'create_ticket'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class=" form-group ">
        <label for="titre " class="control-label "> Titre</label> {{ ticket_form.ticket }}
    </div>
    <div class="form-group ">
        <label for="description " class="control-label ">Description</label> {{ ticket_form.description }}
    </div>
    <div class="form-group ">
        <label for="image " class="control-label ">Image  </label> {{ ticket_form.image }}
        <button type="submit ">Upload</button>
    </div>
    <button type="submit " class="style-button ">Envoyer</button>
</form>
{% endblock%}

review/templates/posts.html
{% extends 'core/base.html' %} {% block menu%} {%include 'core/menu.html'%} {% endblock%} {% block content %}
<H1>Bienvenue sur mes posts</H1>
<div class="container">
    <div class="row">
        <div class="box">
            <div class="post-group">
                {% for e in my_posts %}
                <div class="post-group">
                    <p style="font-style: italic;">Vous avez publié un ticket le {{e.time_created}}</p>
                    <div style="font-weight: bold;">
                        {{e.ticket}}
                    </div>
                    <p>
                        {{e.description}}
                    </p>
                    <div>
                        {{e.image}}
                        <img src="../media/{{e.image}}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
                    </div>
                    <div style="float:right;">
                        <form action="{% url 'modify_post' e.id%}" method="post">
                            {% csrf_token %}
                            <button style="margin: 10px;" class="style-button">Modifier</button>
                        </form>
                        <form action="{% url 'delete_post' e.id%}" method="post">
                            {% csrf_token %}
                            <button class="style-button">Supprimer</button></div>
                    </form>
                    <div style="clear: right;"></div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

review/templates/review.html
{% extends 'core/base.html' %} {% block menu%} {%include 'core/menu.html'%} {% endblock%} {% block content %}
<H1>Créer une critique</H1>
<form action="{%url 'review:create_review' %}" method="post" enctype="multipart/form-data" class="form-review">
    {% csrf_token %}
    <div class=" form-group" style="flex-direction: column; ">
        <label>Article/ Livre : </label>
        <label for="titre" class="control-label"> Titre</label> {{ ticket_form.ticket }}
        <label for="description " class="control-label">Description</label> {{ ticket_form.description }}
        <label for="image " class="control-label ">Image</label> {{ ticket_form.image }}
    </div>

    <div class=" form-group " style="flex-direction: column;">
        <label>Critique : </label>
        <label for="titre " class="control-label "> Titre</label> {{ review_form.headline }}
        <br>
        <label for="note " class="control-label ">Note : 
        <span class="fa fa-star fa-2x " id="first"></span>
        <span class="fa fa-star fa-2x " id="second"></span>
        <span class="fa fa-star fa-2x " id="third"></span>
        <span class="fa fa-star fa-2x" id="fourth"></span>
        <span class="fa fa-star fa-2x" id="fifth"></span>
        </label>
        <div id="confirm_box"></div>
        <br>
        <label for="commentaire" class="control-label ">commentaire  </label> {{ review_form.body}}
    </div>
    <button type="submit " class="style-button ">Envoyer</button>
</form>
{% endblock%}

review/templates/review_create_post.html
{% extends 'core/base.html' %} {% block menu%} {%include 'core/menu.html'%} {% endblock%} {% block content %}
<H1>Créer une critique</H1>


<div class=" form-group" style="flex-direction: column; ">
    <label>Vous êtes en train de poster en réponse à </label>
    <div class=" form-group" style="flex-direction: column; ">
        {% for e in ticket_form %}
        <p style="font-style: italic;">
            <div style="float: right;">le {{e.time_created}} </div>
        </p>
        <div style="font-weight: bold; font-size: x-large;">
            {{e.ticket}}
        </div>
        <p>
            {{e.description}}
        </p>
        <div>
            <img src="/media/{{e.image}}" class="img-responsive" style="width: 50%; height:80%;" />
        </div>
        {% endfor%}
    </div>
</div>
<form action="{% url 'review:create_review_post' ticket_form_id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class=" form-group " style="flex-direction: column;">
        <label>Critique : </label>
        <label for="titre " class="control-label "> Titre</label> {{ review_form.headline }}
        <br>
        <label for="note " class="control-label ">Note : 
        <span class="fa fa-star fa-2x " id="first"></span>
        <span class="fa fa-star fa-2x " id="second"></span>
        <span class="fa fa-star fa-2x " id="third"></span>
        <span class="fa fa-star fa-2x" id="fourth"></span>
        <span class="fa fa-star fa-2x" id="fifth"></span>
        </label>
        <div id="confirm_box"></div>
        <br>
        <label for="commentaire" class="control-label ">commentaire  </label> {{ review_form.body}}
    </div>
    <button type="submit " class="style-button ">Envoyer</button>
</form>
{% endblock%}

review/templates/update_review.html
{% extends 'core/base.html' %} {% block menu%} {%include 'core/menu.html'%} {% endblock%} {% block content %}
<H1>Modifier une critique</H1>
<div class=" form-group" style="flex-direction: column; ">
    <label>Vous êtes en train de poster en réponse à </label>
    <div class=" form-group" style="flex-direction: column; ">
        <p style="font-style: italic;">
            <div style="float: right;">le {{ticket_form.time_created}} </div>
        </p>
        <div style="font-weight: bold; font-size: x-large;">
            {{ticket_form.ticket}}
        </div>
        <p>
            {{ticket_form.description}}
        </p>
        <div>
            <img src="/media/{{ticket_form.image}}" class="img-responsive" style="width: 50%; height:80%;" />
        </div>

    </div>
</div>
<form action="{% url 'review:update_review' id_review id_post %}" method="post">
    {% csrf_token %}
    <div class=" form-group " style="flex-direction: column;">
        <label>Critique : </label>
        <label for="titre " class="control-label "> Titre</label> {{ review_form.headline }}
        <br>
        <label for="note " class="control-label ">Note : 
        <span class="fa fa-star fa-2x " id="first"></span>
        <span class="fa fa-star fa-2x " id="second"></span>
        <span class="fa fa-star fa-2x " id="third"></span>
        <span class="fa fa-star fa-2x" id="fourth"></span>
        <span class="fa fa-star fa-2x" id="fifth"></span>
        </label>
        <div id="confirm_box"></div>
        <br>
        <label for="commentaire" class="control-label ">commentaire  </label> {{ review_form.body}}
    </div>

    <button type="submit " class="style-button ">Envoyer</button>
</form>
{% endblock%}